# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/f18-dig-hist"
url:            "https://cblevins.github.io"

# Author
author:
  name:         Cameron Blevins
  url:          https://cameronblevins.org
#  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
