# Site settings
title:          "Texts, Maps, and Networks:<br>Digital History"
description:    "Northeastern University, Fall 2018"
baseurl:        "/f18-dig-hist"
url:            "https://cblevins.github.io"

# Author
author:
  name:         Cameron Blevins
  url:          https://cameronblevins.org
  email: c.blevins@northeastern.edu
description: > # this means to ignore newlines until "baseurl:"
  Northeastern University, Fall 2018
university: Northeastern University
course_number: "HIST 1130"
semester: "Fall 2018"
room: "Snell Engineering Center, Room 108"
meetingtime: "Mon/Wed/Thurs 9:15-10:20"

instructor: Cameron Blevins
email: c.blevins@northeastern.edu
office: "237 Meserve Hall"
officehours: "By Appointment"


# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
